server.port: 8085

solon.app:
  name: 'demo-app'
  group: 'demo'

demo.db1:
  schema: rock
  jdbcUrl: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456

# 配置数据源对应的 mybatis 信息（要与 DataSource bean 的名字对上）
mybatis.db1:
  configuration: #扩展配置（要与 MybatisConfiguration 类的属性一一对应）
    cacheEnabled: false
    mapperVerifyEnabled: false #如果为 true，则要求所有 mapper 有 @Mapper 主解
    mapUnderscoreToCamelCase: true
  globalConfig: #全局配置（要与 GlobalConfig 类的属性一一对应）
    banner: false

# warm-flow工作流配置
warm-flow:
  # 是否开启工作流，默认true
  enabled: true
  # 是否显示banner图，默认是
  banner: true
  # id生成器类型, 不填默认为orm扩展自带生成器或者warm-flow内置的19位雪花算法, SnowId14:14位，SnowId15:15位， SnowFlake19：19位
  key_type: SnowId19
  # 填充器 （可通过配置文件注入，也可用@Bean/@Component方式）
#  data-fill-handler-path: org.dromara.warm.flow.core.handle.CustomDataFillHandler
  # 全局租户处理器（可通过配置文件注入，也可用@Bean/@Component方式
#  tenant_handler_path: org.dromara.warm.flow.core.handle.CustomTenantHandler
  # 是否开启逻辑删除（orm框架本身不支持逻辑删除，可通过这种方式开启，比如jpa）
  logic_delete: false
  # 逻辑删除字段值（开启后默认为2）
  logic_delete_value: 2
  # 逻辑未删除字段（开启后默认为0）
  logic_not_delete_value: 0
